package com.smsoft.smartdisplay.ui.screen.dashboard

const val APP_CHANNEL = "SmartDisplaychannnel"
const val PUSH_BUTTON_STATUS_DEFAULT_TOPIC = "*/stat/*/POWER"
const val PUSH_BUTTON_COMMAND_DEFAULT_TOPIC = "*/cmnd/*/POWER"
const val PUSH_BUTTON_DEFAULT_STATE = false
const val PUSH_BUTTON_ON_PAYLOAD = "ON"
const val PUSH_BUTTON_DEFAULT_PAYLOAD_ON = "1"
const val PUSH_BUTTON_DEFAULT_PAYLOAD_OFF = "0"
const val PROXIMITY_SENSOR_DEFAULT_TOPIC = "pushbutton2"
const val PROXIMITY_SENSOR_DEFAULT_STATE = false
const val PROXIMITY_SENSOR_DEFAULT_PAYLOAD_ON = "1"
const val PROXIMITY_SENSOR_DEFAULT_PAYLOAD_OFF = "0"
const val PROXIMITY_SENSOR_THRESHOLD = 500
const val PROXIMITY_SENSOR_MIN_DETECTION_DURATION = 1000L
const val DIMMER_LIGHT_DEFAULT_BRIGHTNESS = 100
const val DIMMER_LIGHT_STEP_PERCENT = 10
const val SHOW_ASR_RESULT_TIMEOUT = 1000L //2s
