plugins {
    alias(libs.plugins.android.library)
}

def generatedAssetsDir = layout.buildDirectory.dir("generated/assets").get().asFile

android {
    namespace = "org.vosk.models"
    compileSdk = 37
    defaultConfig {
        minSdk = 26
    }
    buildFeatures {
        buildConfig = false
    }
    sourceSets {
        main {
            assets.srcDirs += generatedAssetsDir
        }
    }
}

tasks.register('genUUID') {
    def uuid = UUID.randomUUID().toString()
    //def odir = new File(generatedAssetsDir, "model-en-us")
    def odir = new File(generatedAssetsDir, "model-small-ru")
    def ofile = new File(odir, "uuid")
    doLast {
        odir.mkdirs()
        ofile.text = uuid
    }
}

preBuild.dependsOn(genUUID)
